//==================================================
//     Outputs that match the input variables
//==================================================
output "actions" {
  description = "The value of the `actions` input variable (or the default value if the input was `null`)."
  value       = local.actions
}

output "not_actions" {
  description = "The value of the `not_actions` input variable (or the default value if the input was `null`)."
  value       = local.not_actions
}

output "effect" {
  description = "The value of the `effect` input variable (or the default value if the input was `null`)."
  value       = local.effect
}

output "resources" {
  description = "The value of the `resources` input variable (or the default value if the input was `null`)."
  value       = local.resources
}

output "not_resources" {
  description = "The value of the `not_resources` input variable (or the default value if the input was `null`)."
  value       = local.not_resources
}

output "principals" {
  description = "The value of the `principals` input variable (or the default value if the input was `null`)."
  value       = local.principals
}

output "not_principals" {
  description = "The value of the `not_principals` input variable (or the default value if the input was `null`)."
  value       = local.not_principals
}

output "conditions" {
  description = "The value of the `conditions` input variable (or the default value if the input was `null`)."
  value       = local.conditions
}

output "sid" {
  description = "The value of the `sid` input variable (or the default value if the input was `null`)."
  value       = var.sid
}

output "org_entities" {
  description = "The value of the `org_entities` input variable (or the default value if the input was `null`)."
  value       = local.org_entities
}

output "source_policy_documents" {
  description = "The value of the `source_policy_documents` input variable (or the default value if the input was `null`)."
  value       = local.source_policy_documents
}

output "override_policy_documents" {
  description = "The value of the `override_policy_documents` input variable (or the default value if the input was `null`)."
  value       = local.override_policy_documents
}

//==================================================
//       Outputs generated by this module
//==================================================
output "organization_ids" {
  description = "A list of Organization IDs that are included in the policy."
  value       = local.organizations
}

output "organizational_unit_ids" {
  description = "A list of Organizational Unit IDs that are included in the policy."
  value       = local.organizational_units
}

output "account_ids" {
  description = "A list of Account IDs that are included in the policy."
  value       = local.accounts
}

output "json" {
  description = "The JSON-encoded policy document."
  value       = data.aws_iam_policy_document.this.json
}
