//==================================================
//     Outputs that match the input variables
//==================================================
output "actions" {
  description = "The value of the `actions` input variable (or the default value if the input was `null`)."
  value       = local.actions
}

output "not_actions" {
  description = "The value of the `not_actions` input variable (or the default value if the input was `null`)."
  value       = local.not_actions
}

output "effect" {
  description = "The value of the `effect` input variable (or the default value if the input was `null`)."
  value       = local.effect
}

output "resources" {
  description = "The value of the `resources` input variable (or the default value if the input was `null`)."
  value       = local.resources
}

output "not_resources" {
  description = "The value of the `not_resources` input variable (or the default value if the input was `null`)."
  value       = local.not_resources
}

output "principals" {
  description = "The value of the `principals` input variable (or the default value if the input was `null`)."
  value       = local.principals
}

output "not_principals" {
  description = "The value of the `not_principals` input variable (or the default value if the input was `null`)."
  value       = local.not_principals
}

output "conditions" {
  description = "The value of the `conditions` input variable (or the default value if the input was `null`)."
  value       = local.conditions
}

output "sid" {
  description = "The value of the `sid` input variable (or the default value if the input was `null`)."
  value       = var.sid
}

output "org_principals" {
  description = "The value of the `org_principals` input variable (or the default value if the input was `null`)."
  value       = local.org_principals
}

output "source_policy_documents" {
  description = "The value of the `source_policy_documents` input variable (or the default value if the input was `null`)."
  value       = local.source_policy_documents
}

output "override_policy_documents" {
  description = "The value of the `override_policy_documents` input variable (or the default value if the input was `null`)."
  value       = local.override_policy_documents
}

//==================================================
//       Outputs generated by this module
//==================================================
output "organization_ids_delegation_required" {
  description = "A list of Organization IDs that have permissions, but where individual accounts must delegate permissions to their own IAM entities."
  value       = local.organizations_delegation_required
}

output "organization_ids_delegation_not_required" {
  description = "A list of Organization IDs that have permissions where all IAM entities in all accounts in the organization have permissions."
  value       = local.organizations_delegation_not_required
}

output "organizational_unit_ids_delegation_required" {
  description = "A list of Organizational Unit IDs that have permissions, but where individual accounts must delegate permissions to their own IAM entities."
  value       = local.organizational_units_delegation_required
}

output "organizational_unit_ids_delegation_not_required" {
  description = "A list of Organizational Unit IDs that have permissions where all IAM entities in all accounts in the organization have permissions."
  value       = local.organizational_units_delegation_not_required
}

output "account_ids_delegation_required" {
  description = "A list of AWS accounts that have permissions, but must delegate the permissions to their own IAM entities."
  value       = local.accounts_delegation_required
}

output "account_ids_delegation_not_required" {
  description = "A list of AWS accounts that have permissions and where all IAM entities in those accounts have permissions."
  value       = local.accounts_delegation_not_required
}

output "json" {
  description = "The JSON-encoded policy document."
  value       = data.aws_iam_policy_document.this.json
}
